### ISSUE TITLE
Javascript error: loading failed

### ISSUE THREAD

**Issue by Kirsten-G** [axllent/silverstripe-form-fields#2]
I am new to SS4^. I installed this module yesterday (but didn't install the vendor-plugin module, as I found out that this is required after I spend some time with composer today) in one project where I installed SS4 (not sure which version, as I don't know where to look for) a while ago and used it as in the SS4 lessons described. Everything works fine.

Then I installed -this time definitely SS4.1- and this module + linkable and display-logic in a new project (everything manually again). 
When I now go into the page where I included a DataObject using the linkable (nothing from this module here) this opens with "Not found" in the right hand corner of the CMS and when I try to click on the AddLink button (created with the linkable module) this doesn't open. 

I then had a look into the dev-tools of my browser and found this error:
silverstripe 4.1 Loading failed for the <script> with source http://myproject.local/resources/form-fields/javascript/cms-form-fields.js?m=1522809567.

Today I read through all the composer stuff and had a look at the composer,json which comes with this module and installed the vendor-plugin. I still get the same error.

1. How do I know which SS version I installed as the silverstripe_version file isn't filled with data in both my installations?
2. Do I have to put anything into a config file for this module to work and direct to the public folder?
3. Where does this mapping myproject.local/resources/ or myproject.local/public happen?

Thank you very much

**Comment by Kirsten-G** [comment]
I just had another look at this. So in my first installation of this module I must have used SS4, as it has a resources folder instead of a public folder.
So, this module doesn't work on SS4.1 (public/resources) with or without vendor-plugin module.

**Comment by axllent** [comment]
Hi. Sorry but I'm not on my computer right now so this is just off the top of my head. SilverStripe relies now completely on composer to handle both the installation of the framework, cms, etc, as well as all modules, dependencies etc. Part of the installation (using composer) ensures that the necessary `public/resources` symlinks for module assets are in fact created (everything outside of `public` is not directly accessible via the web). Trust me, you don't want to deal with all of that manually.

**Comment by Kirsten-G** [comment]
Thanks axllent, I deleted the folder and used composer for installation and now the error is gone.

**Comment by axllent** [comment]
Glad to hear it, thanks for the feedback!
