### ISSUE TITLE
SS 4.2

### ISSUE THREAD

**Issue by sanderha** [axllent/silverstripe-form-fields#3]
Could we change the requirements to allowing silverstripe 4.2? :)

**Comment by axllent** [comment]
I'm sorry but I don't understand what you mean. It does install with SilverStripe 4.2:
```
$ composer require axllent/silverstripe-form-fields
Using version ^1.2 for axllent/silverstripe-form-fields
./composer.json has been updated
```

**Comment by sanderha** [comment]
I see I had made a mistake, it works fine. Sorry for the inconvenience!
